package com.student;
// default package
// Generated Apr 2, 2016 11:17:04 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Student generated by hbm2java
 */
public class Student implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal studentId;
	private String studentCode;
	private String studentName;
	private BigDecimal studentAge;
	private Set<Subject> subjects = new HashSet<Subject>(0);

	public Student() {
	}
	
	public Student(String studentCode,
			String studentName, BigDecimal studentAge) {
		this.studentCode = studentCode;
		this.studentName = studentName;
		this.studentAge = studentAge;
	}

	public Student(BigDecimal studentId, String studentCode,
			String studentName, BigDecimal studentAge) {
		this.studentId = studentId;
		this.studentCode = studentCode;
		this.studentName = studentName;
		this.studentAge = studentAge;
	}
	
	public Student(BigDecimal studentId, String studentCode,
			String studentName, BigDecimal studentAge, Set<Subject> subjects) {
		this.studentId = studentId;
		this.studentCode = studentCode;
		this.studentName = studentName;
		this.studentAge = studentAge;
		this.subjects = subjects;
	}

	public BigDecimal getStudentId() {
		return this.studentId;
	}

	public void setStudentId(BigDecimal studentId) {
		this.studentId = studentId;
	}

	public String getStudentCode() {
		return this.studentCode;
	}

	public void setStudentCode(String studentCode) {
		this.studentCode = studentCode;
	}

	public String getStudentName() {
		return this.studentName;
	}

	public void setStudentName(String studentName) {
		this.studentName = studentName;
	}

	public BigDecimal getStudentAge() {
		return this.studentAge;
	}

	public void setStudentAge(BigDecimal studentAge) {
		this.studentAge = studentAge;
	}

	public Set<Subject> getSubjects() {
		return this.subjects;
	}

	public void setSubjects(Set<Subject> subjects) {
		this.subjects = subjects;
	}

}
