package com.student;
// default package
// Generated Apr 2, 2016 11:17:04 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Subject generated by hbm2java
 */
public class Subject implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal subjectId;
	private String subjectName;
	private String subjectDesc;
	private Set<Student> students = new HashSet<Student>(0);

	public Subject() {
	}

	public Subject(String subjectName, String subjectDesc) {
		this.subjectName = subjectName;
		this.subjectDesc = subjectDesc;
	}
	
	public Subject(BigDecimal subjectId, String subjectName, String subjectDesc) {
		this.subjectId = subjectId;
		this.subjectName = subjectName;
		this.subjectDesc = subjectDesc;
	}

	public Subject(BigDecimal subjectId, String subjectName,
			String subjectDesc, Set<Student> students) {
		this.subjectId = subjectId;
		this.subjectName = subjectName;
		this.subjectDesc = subjectDesc;
		this.students = students;
	}

	public BigDecimal getSubjectId() {
		return this.subjectId;
	}

	public void setSubjectId(BigDecimal subjectId) {
		this.subjectId = subjectId;
	}

	public String getSubjectName() {
		return this.subjectName;
	}

	public void setSubjectName(String subjectName) {
		this.subjectName = subjectName;
	}

	public String getSubjectDesc() {
		return this.subjectDesc;
	}

	public void setSubjectDesc(String subjectDesc) {
		this.subjectDesc = subjectDesc;
	}

	public Set<Student> getStudents() {
		return this.students;
	}

	public void setStudents(Set<Student> students) {
		this.students = students;
	}

}
