DROP TABLE "STUDY"."STOCK";
CREATE TABLE "STUDY"."STOCK" 
(	"STOCK_ID" NUMBER(10,0), 
	"STOCK_CODE" VARCHAR2(10 BYTE) NOT NULL, 
	"STOCK_NAME" VARCHAR2(20 BYTE)  NOT NULL,
  	PRIMARY KEY (STOCK_ID),
  	CONSTRAINT UNI_STOCK_CODE UNIQUE (STOCK_CODE),
  	CONSTRAINT UNI_STOCK_NAME UNIQUE (STOCK_NAME) 
);

CREATE SEQUENCE  "STUDY"."STOCK_SEQ" 
MINVALUE 1 MAXVALUE 9999999999999999999999999999 
INCREMENT BY 1 START WITH 101 CACHE 100 NOORDER  NOCYCLE ;

DROP TABLE "STUDY"."STOCK_DAILY_RECORD";
CREATE TABLE  "STUDY"."STOCK_DAILY_RECORD" (
  "RECORD_ID" NUMBER(10,0),
  "PRICE_OPEN" NUMBER(6,2) DEFAULT NULL,
  "PRICE_CLOSE" NUMBER(6,2) DEFAULT NULL,
  "PRICE_CHANGE" NUMBER(6,2) DEFAULT NULL,
  "CHANGE_DATE" date NOT NULL,
  "STOCK_ID" NUMBER(10,0) NOT NULL,
  PRIMARY KEY ("RECORD_ID"),
  CONSTRAINT "UNI_STOCK_DAILY_DATE" UNIQUE ("CHANGE_DATE"),
  CONSTRAINT "FK_STOCK_TRANSACTION_STOCK_ID" FOREIGN KEY ("STOCK_ID")  REFERENCES "STOCK" ("STOCK_ID") ON DELETE CASCADE
);

CREATE SEQUENCE  "STUDY"."STOCK_DAILY_RECORD_SEQ" 
MINVALUE 1 MAXVALUE 9999999999999999999999999999 
INCREMENT BY 1 START WITH 101 CACHE 100 NOORDER  NOCYCLE ;
