DROP TABLE "STUDY"."STUDENT";
CREATE TABLE "STUDY"."STUDENT" 
(	"STUDENT_ID" INT, 
	"STUDENT_CODE" VARCHAR2(10 BYTE) NOT NULL, 
	"STUDENT_NAME" VARCHAR2(30 BYTE)  NOT NULL,
	"STUDENT_AGE" SMALLINT NOT NULL,
  	PRIMARY KEY (STUDENT_ID),
  	CONSTRAINT UNI_STUDENT_CODE UNIQUE (STUDENT_CODE)  	
);
CREATE SEQUENCE  "STUDY"."STUDENT_SEQ" 
MINVALUE 1 MAXVALUE 99999999999999 
INCREMENT BY 1 START WITH 101 CACHE 100 NOORDER  NOCYCLE ;

DROP TABLE "STUDY"."SUBJECT";
CREATE TABLE  "STUDY"."SUBJECT" 
(
 	"SUBJECT_ID" INT,
 	"SUBJECT_NAME" varchar(100) NOT NULL,
 	"SUBJECT_DESC" varchar(255) NOT NULL,
 	PRIMARY KEY (SUBJECT_ID),
 	CONSTRAINT UNI_SUBJECT_NAME UNIQUE (SUBJECT_NAME) 
);
CREATE SEQUENCE  "STUDY"."SUBJECT_SEQ" 
MINVALUE 1 MAXVALUE 99999999999999 
INCREMENT BY 1 START WITH 101 CACHE 100 NOORDER  NOCYCLE ;

CREATE TABLE "STUDY"."STUDENT_SUBJECT"
(
	"STUDENT_ID" INT,
	"SUBJECT_ID" INT,
	PRIMARY KEY ("STUDENT_ID", "SUBJECT_ID"),
	CONSTRAINT FK_STUDENT_ID FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT (STUDENT_ID),
	CONSTRAINT FK_SUBJECT_ID FOREIGN KEY (SUBJECT_ID) REFERENCES SUBJECT (SUBJECT_ID)
);