package com.student;

// Generated Apr 2, 2016 9:43:41 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Subject generated by hbm2java
 */
@Entity
@Table(name = "SUBJECT", uniqueConstraints = @UniqueConstraint(columnNames = "SUBJECT_NAME"))
public class Subject implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal subjectId;
	private String subjectName;
	private String subjectDesc;
	private Set<Student> students = new HashSet<Student>(0);

	public Subject() {
	}

	public Subject(String subjectName, String subjectDesc) {
		this.subjectName = subjectName;
		this.subjectDesc = subjectDesc;
	}
	
	public Subject(BigDecimal subjectId, String subjectName, String subjectDesc) {
		this.subjectId = subjectId;
		this.subjectName = subjectName;
		this.subjectDesc = subjectDesc;
	}

	public Subject(BigDecimal subjectId, String subjectName,
			String subjectDesc, Set<Student> students) {
		this.subjectId = subjectId;
		this.subjectName = subjectName;
		this.subjectDesc = subjectDesc;
		this.students = students;
	}

	@Id
	@Column(name = "SUBJECT_ID", unique = true, nullable = false, precision = 22, scale = 0)
	@GeneratedValue(generator="subject_seq",strategy=GenerationType.SEQUENCE)
	@SequenceGenerator(name="subject_seq", sequenceName="SUBJECT_SEQ")
	public BigDecimal getSubjectId() {
		return this.subjectId;
	}

	public void setSubjectId(BigDecimal subjectId) {
		this.subjectId = subjectId;
	}

	@Column(name = "SUBJECT_NAME", unique = true, nullable = false, length = 100)
	public String getSubjectName() {
		return this.subjectName;
	}

	public void setSubjectName(String subjectName) {
		this.subjectName = subjectName;
	}

	@Column(name = "SUBJECT_DESC", nullable = false)
	public String getSubjectDesc() {
		return this.subjectDesc;
	}

	public void setSubjectDesc(String subjectDesc) {
		this.subjectDesc = subjectDesc;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "subjects")
	public Set<Student> getStudents() {
		return this.students;
	}

	public void setStudents(Set<Student> students) {
		this.students = students;
	}

}
