// default package
// Generated Apr 1, 2016 5:20:19 PM by Hibernate Tools 4.3.1
package com.stock;
import java.math.BigDecimal;
import java.util.Date;

/**
 * StockDailyRecord generated by hbm2java
 */
public class StockDailyRecord implements java.io.Serializable {

	private long recordId;
	private Stock stock;
	private BigDecimal priceOpen;
	private BigDecimal priceClose;
	private BigDecimal priceChange;
	private Date changeDate;

	public StockDailyRecord() {
	}

	public StockDailyRecord(long recordId, Stock stock, Date changeDate) {
		this.recordId = recordId;
		this.stock = stock;
		this.changeDate = changeDate;
	}

	public StockDailyRecord(long recordId, Stock stock, BigDecimal priceOpen,
			BigDecimal priceClose, BigDecimal priceChange, Date changeDate) {
		this.recordId = recordId;
		this.stock = stock;
		this.priceOpen = priceOpen;
		this.priceClose = priceClose;
		this.priceChange = priceChange;
		this.changeDate = changeDate;
	}
	
	public StockDailyRecord(Stock stock, BigDecimal priceOpen,
			BigDecimal priceClose, BigDecimal priceChange, Date changeDate) {
		this.stock = stock;
		this.priceOpen = priceOpen;
		this.priceClose = priceClose;
		this.priceChange = priceChange;
		this.changeDate = changeDate;
	}

	public long getRecordId() {
		return this.recordId;
	}

	public void setRecordId(long recordId) {
		this.recordId = recordId;
	}

	public Stock getStock() {
		return this.stock;
	}

	public void setStock(Stock stock) {
		this.stock = stock;
	}

	public BigDecimal getPriceOpen() {
		return this.priceOpen;
	}

	public void setPriceOpen(BigDecimal priceOpen) {
		this.priceOpen = priceOpen;
	}

	public BigDecimal getPriceClose() {
		return this.priceClose;
	}

	public void setPriceClose(BigDecimal priceClose) {
		this.priceClose = priceClose;
	}

	public BigDecimal getPriceChange() {
		return this.priceChange;
	}

	public void setPriceChange(BigDecimal priceChange) {
		this.priceChange = priceChange;
	}

	public Date getChangeDate() {
		return this.changeDate;
	}

	public void setChangeDate(Date changeDate) {
		this.changeDate = changeDate;
	}

}
